name             'livingroom'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures livingroom'
long_description 'Installs/Configures livingroom'
version          '0.1.0'
