name             '3i-nodejs'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures 3i-nodejs'
long_description 'Installs/Configures 3i-nodejs'
version          '0.1.0'
